version: 2

defaults: &defaults
  macos:
    xcode: "10.2.1"

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - run:
          name: Run Tests
          command: make test

      - run:
          name: Lint Cocoapods
          command: make lint-cocoapods
